### ISSUE TITLE
Broken in debian jessie

### ISSUE THREAD

**Issue by leophys** [ael-code/pydirl#15]
Hi, 
I successfully run pydirl on archlinux inside a virtualenv (python 3.5).
Tryng to make it work on a debian jessie (8.4) inside a virtualenv (python 3.4) I got the following error at exec time

```
% pydirl --help
Traceback (most recent call last):
  File "/mnt2/pydirl/pydirl_ve/bin/pydirl", line 9, in <module>
    load_entry_point('pydirl==0.2', 'console_scripts', 'pydirl')()
  File "/mnt2/pydirl/pydirl_ve/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/mnt2/pydirl/pydirl_ve/lib/python3.4/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/mnt2/pydirl/pydirl_ve/lib/python3.4/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named 'pydirl'
```

Any guess why?

Greetings

**Comment by leophys** [comment]
Ping

**Comment by ael-code** [comment]
I will try soon
